# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4999bec3d2dd5e79fe697a696ab84d950d6ebe773ee09e24245c31db78580725048f5b4b66f7714191a63573602c53bc9d31d86852ccb1376667d5af43f10d0a

test:
  secret_key_base: 64c78d92845b4794f60ea28ee267a4187403413710b999f9200db9cc2b321dc7396c7f076dd2d42388b5a6ae6903e04b15e04f96e3a6d7f4f348d82ae904941b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
